shahwaiz_nadeem/week_05/tues/pokemons/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'pokemons#index'

  get '/pokemons' => 'pokemons#index'
  get '/pokemons/new' => 'pokemons#new', :as => 'new_pokemon'
  post '/pokemons' => 'pokemons#create'
  get '/pokemons/:id' => 'pokemons#show', :as => 'pokemon'
  get '/pokemons/:id/edit' => 'pokemons#edit', :as => 'edit_pokemon'
  post '/pokemons/:id' => 'pokemons#update'
  delete '/pokemons/:id' => 'pokemons#destroy'

end

shahwaiz_nadeem/week_05/tues/pokemons/app/models/pokemon.rb
class Pokemon < ActiveRecord::Base

end

shahwaiz_nadeem/week_05/tues/pokemons/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  skip_before_action :verify_authenticity_token

end

shahwaiz_nadeem/week_05/tues/pokemons/app/controllers/pokemons_controller.rb
class pokemonsController < ApplicationController
  def index
    @pokemons =Pokemon.all
  end

  def show
    @pokemon = Pokemon.find params[:id]
  end

  def new
  end

  def create
    pokemon = Pokemon.create :name => params[:name], :image => params[:image], :type => params[:type]
    redirect_to "#{pokemons_path}/#{pokemon.id}"
  end

  def edit
    @pokemon = Pokemon.find params[:id]
  end

  def update
    pokemon = Pokemon.find params[:id]

    pokemon.name = params[:name]
    pokemon.image = params[:image]
    pokemon.type = params[:type]
    pokemon.save
    redirect_to pokemon_path(pokemon.id)
  end

  def destroy
    pokemon = Pokemon.find params[:id]
    pokemon.destroy
    redirect_to pokemons_path
  end
end

shahwaiz_nadeem/week_05/tues/pokemons/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SolarSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav>
      <%= link_to "All pokemons", pokemons_path %>
      <%= link_to "New pokemons", new_pokemon_path %>
    </nav>

    <%= yield %>
  </body>
</html>

shahwaiz_nadeem/week_05/tues/pokemons/app/views/pokemons/edit.html.erb
<h2>EDIT Pokemon</h2>

<form action="<%= pokemon_path(@pokemon.id) %>" method="post">
  <label style="display: block; margin: 10px">
    Name:
    <input name="name" value="<%= @pokemon.name %>" required>
  </label>
  <label style="display: block; margin: 10px">
    Image:
    <input type="url" name="image" value="<%= @pokemon.image %>">
  </label>
  <label style="display: block; margin: 10px">
    Orbit:
    <input type="number" name="orbit" value="<%= @pokemon.orbit %>">
  </label style="display: block; margin: 10px">
  <label  style="display: block; margin: 10px">
    Diameter:
    <input type="number" name="diammeter" value="<%= @pokemon.diammeter %>">
  </label>
  <label style="display: block; margin: 10px">
    Mass:
    <input type="number" name="mass" value="<%= @pokemon.mass %>">
  </label>
  <label style="display: block; margin: 10px">
    Moons:
    <input type="number" name="moons" value="<%= @pokemon.moons %>">
  </label>

  <button type="submit">UPDATE PLANET</button>
</form>

shahwaiz_nadeem/week_05/tues/pokemons/app/views/pokemons/index.html.erb
<h2>All pokemons</h2>

<% @pokemons.each do |pokemon| %>
  <p>
    <%= link_to pokemon.name,"/pokemons/#{pokemon.id}" %>
  </p>
<% end %>

shahwaiz_nadeem/week_05/tues/pokemons/app/views/pokemons/new.html.erb
<h2>New Pokemon</h2>

<form action="/pokemons" method="post">
  <label style="display: block; margin: 10px">
    Name:
    <input name="name" required>
  </label>
  <label style="display: block; margin: 10px">
    Image:
    <input type="url" name="image">
  </label>
  <label style="display: block; margin: 10px">
    Type:
    <input type="text" name="type">
  </label>

  <button type="submit">CREATE PLANET</button>
</form>

shahwaiz_nadeem/week_05/tues/pokemons/app/views/pokemons/show.html.erb
<h2><%= @pokemon.name %></h2>

<%= image_tag @pokemon.image, :class => 'feature' if @pokemon.image.present? %>

<ul>
  <li>Name: <%= @pokemon.name %></li>
  <li>Type: <%= @pokemon.type %></li>
</ul>

<div class="controls">
  <%= link_to 'Edit Pokemon', edit_pokemon_path(@pokemon.id)  %>
  <%= button_to 'Delete Pokemon', pokemon_path(@pokemon.id), :method => 'delete' %>
</div>