carol_liu/week_05/W1D2_mountains/contour_system/config/routes.rb
Rails.application.routes.draw do
  get '/' => 'mountains#index'
  get '/mountains' => 'mountains#index'
  get '/mountains/new' => 'mountains#new', :as => 'new_mountain'
  post '/mountains' => 'mountains#create'
  get '/mountains/:id' => 'mountains#show', :as => 'mountain'
  get '/mountains/:id/edit' => 'mountains#edit', :as => 'edit_mountain'
  post '/mountains/:id' => 'mountains#update'
  delete '/mountains/:id' => 'mountains#delete'
end

carol_liu/week_05/W1D2_mountains/contour_system/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

carol_liu/week_05/W1D2_mountains/contour_system/app/models/mountain.rb
class Mountain < ActiveRecord::Base
end

carol_liu/week_05/W1D2_mountains/contour_system/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

carol_liu/week_05/W1D2_mountains/contour_system/app/controllers/mountains_controller.rb
class MountainsController < ApplicationController
  def index
    @mountains = Mountain.all
  end

  def show
    @mountain = Mountain.find params[:id]
  end

  def new
  end

  def create
    mountain = Mountain.create :name => params[:name], :image => params[:image], :height => params[:height], :range => params[:range], :first_ascent => params[:first_ascent]
    redirect_to mountain_path(mountain.id)
  end

  def edit
    @mountain = Mountain.find params[:id]
  end

  def update
    mountain = Mountain.find params[:id]
    mountain.name = params[:name]
    mountain.image = params[:image]
    mountain.height = params[:height]
    mountain.range = params[:range]
    mountain.first_ascent = params[:first_ascent]
    mountain.save
    redirect_to mountain_path(mountain.id)
  end

  def delete
    mountain = Mountain.find params[:id]
    mountain.destroy
    redirect_to mountains_path
  end
end

carol_liu/week_05/W1D2_mountains/contour_system/app/helpers/application_helper.rb
module ApplicationHelper
end

carol_liu/week_05/W1D2_mountains/contour_system/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContourSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= link_to 'All Mountains', mountains_path %>
      <%= link_to 'New Mountains', new_mountain_path %>
    </nav>
    <%= yield %>
  </body>
</html>