alex_maunder/week_05/library/config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :books
end

alex_maunder/week_05/library/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

alex_maunder/week_05/library/app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
end

alex_maunder/week_05/library/app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author, :optional => true
end

alex_maunder/week_05/library/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

alex_maunder/week_05/library/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def new
    @author = Author.new
  end

  def create
    author = Author.create author_params
    redirect_to author
  end

  def edit
    @author = Author.find params[:id]
  end

  def update
    author = Author.find params[:id]
    author.update author_params
    redirect_to author
  end

  def show
    @author = Author.find params[:id]
  end

  def destroy
    author = Author.find params[:id]
    author.destroy
    redirect_to authors_path    
  end

  private
  def author_params
    params.require(:author).permit(:name, :nationality, :dob, :genre, :image, :wiki)
  end
end

alex_maunder/week_05/library/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    book = Book.create book_params
    redirect_to book
  end

  def edit
    @book = Book.find params[:id]
  end

  def update
    book = Book.find params[:id]
    book.update book_params
    redirect_to book
  end

  def show
    @book = Book.find params[:id]
  end

  def destroy
    book = Book.find params[:id]
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :year, :publisher, :image, :bio, :author_id)
  end
end

alex_maunder/week_05/library/app/helpers/application_helper.rb
module ApplicationHelper
end

alex_maunder/week_05/library/app/helpers/authors_helper.rb
module AuthorsHelper
end

alex_maunder/week_05/library/app/helpers/books_helper.rb
module BooksHelper
end

alex_maunder/week_05/library/app/views/authors/_form.html.erb
<%= form_for @author do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :required => true, :autofocus => true %>

  <%= f.label :nationality %>
  <%= f.text_field :nationality, :placeholder => 'Irish' %>

  <%= f.label :dob, 'Date of Birth' %>
  <%= f.text_field :dob, :placeholder => 'YYY-MM-DD' %>

  <%= f.label :genre %>
  <%= f.text_field :genre, :placeholder => 'Fiction' %>

  <%= f.label :image %>
  <%= f.url_field :image %>

  <%= f.label :wiki %>
  <%= f.url_field :wiki %>

  <%= f.submit %>
<% end %>

alex_maunder/week_05/library/app/views/authors/edit.html.erb
<h1>Edit Author</h1>
<%= render :partial => 'form' %>

alex_maunder/week_05/library/app/views/authors/index.html.erb
<h1>All Authors</h1>

<% @authors.each do |author| %>
  <%= image_tag author.image, :class => 'thumb' if author.image.present? %>
  <ul>
    <li>Name: <%= link_to author.name, author %></li>
    <li>Nationality: <%= author.nationality %></li>
    <li>Date of Birth: <%= author.dob %></li>
    <li>Genre: <%= author.genre %></li>
    <li>Wiki: <%= link_to author.wiki if author.wiki.present? %></li>
  </ul>
<% end %>

alex_maunder/week_05/library/app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render :partial => 'form' %>

alex_maunder/week_05/library/app/views/authors/show.html.erb
<h1><%= @author.name %></h1>

<%= image_tag @author.image, :class => 'feature' if @author.image.present? %>
<ul>
  <li>Name: <%= @author.name %></li>
  <li>Nationality: <%= @author.nationality %></li>
  <li>Date of Birth: <%= @author.dob.strftime '%A, %B %e, %Y'  if @author.dob.present?%></li>
  <li>Genre: <%= @author.genre %></li>
  <li>Wiki: <%= link_to @author.wiki if @author.wiki.present? %></li>
</ul>

<% @author.books.each do |book| %>
  <%= link_to image_tag(book.image, :class => 'thumb'), book %>
<% end %>

<div class="controls">
  <%= link_to 'Edit Author', edit_author_path(@author) %>
  <%= button_to 'Delete Author', @author, :method => 'delete' %>
</div>