carol_liu/week_05/travel_app/config/routes.rb
Rails.application.routes.draw do
  resources :countries
  resources :places
end

carol_liu/week_05/travel_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

carol_liu/week_05/travel_app/app/models/country.rb
class Country < ActiveRecord::Base
  has_many :places 
end

carol_liu/week_05/travel_app/app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :country, :optional => true
end

carol_liu/week_05/travel_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

carol_liu/week_05/travel_app/app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
    @countries = Country.all
  end

  def new
    @country = Country.new
  end

  def create
    country = Country.create country_params
    redirect_to country
  end

  def edit
    @country = Country.find params[:id]
  end

  def update
    country = Country.find params[:id]
    country.update country_params
    redirect_to country
  end

  def show
    @country = Country.find params[:id]
  end

  def destroy
    country = Country.find params[:id]
    country.destroy
    redirect_to countries_path
  end

  private
  def country_params
    params.require(:country).permit(:name, :capital, :official_language, :area_in_sqkm, :population, :flag)
  end
end

carol_liu/week_05/travel_app/app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
  end

  def new
    @place = Place.new
  end

  def create
    place = Place.create place_params
    redirect_to place
  end

  def edit
    @place = Place.find params[:id]
  end

  def update
    place = Place.find params[:id]
    place.update place_params
    redirect_to place
  end

  def show
    @place = Place.find params[:id]
  end

  def destroy
    place = Place.find params[:id]
    place.destroy
    redirect_to places_path
  end

  private
  def place_params
    params.require(:place).permit(:name, :region, :feature, :period, :altitude_in_m, :image, :country_id)
  end
end

carol_liu/week_05/travel_app/app/helpers/application_helper.rb
module ApplicationHelper
end

carol_liu/week_05/travel_app/app/helpers/countries_helper.rb
module CountriesHelper
end

carol_liu/week_05/travel_app/app/helpers/places_helper.rb
module PlacesHelper
end

carol_liu/week_05/travel_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= link_to 'All Countries', countries_path %>
      <%= link_to 'New Country', new_country_path %>

      <%= link_to 'All Places', places_path %>
      <%= link_to 'New Place', new_place_path %>
    </nav>
    <%= yield %>
  </body>
</html>